#spring.application.name=mail-dev


server:
  port: 8090

spring:
  application:
    name: mail-dev # Name of your Spring Boot application
  main:
    allow-bean-definition-overriding: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect # Specify the MySQL dialect here
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mail_dev?serverTimezone=UTC
    username: root
    password: root123
  mail:
    host: smtp.gmail.com
    port: 587
    username: mahmoodselawe5@gmail.com
    password: tfns urkb jqsc xhes
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: http://localhost:8090


